version: "3.9"

services:
  postgres:
    image: postgres:13.16-alpine
    restart: always
    ports:
      - "54323:5432"
    environment:
      POSTGRES_DB: match-store
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
