[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = [
  "go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
