[phases.setup]
nixPkgs = ["go", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "echo '📦 Install phase starting...'",
  "echo 'Installing migrate CLI...'",
  "go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest",
  "echo 'Migrate CLI installed. Checking location:'",
  "ls -la $(go env GOPATH)/bin/migrate || echo 'migrate binary not found'",
  "export PATH=$PATH:$(go env GOPATH)/bin",
  "echo 'PATH updated. Current PATH:' $PATH",
  "npm ci"
]

[phases.build]
cmds = [
  "echo '🔧 Build phase starting...'",
  "echo 'Current PATH:' $PATH",
  "echo 'Go binary path:' $(go env GOPATH)/bin",
  "export PATH=$PATH:$(go env GOPATH)/bin",
  "echo 'Updated PATH:' $PATH",
  "echo 'Checking if migrate is available:'",
  "which migrate || echo 'migrate not found in PATH'",
  "npm run build"
]

[start]
cmd = "npm run test:db && npm start"
