ALTER TABLE lobbies DROP CONSTRAINT IF EXISTS "FK_396c7159a1a7e322fcd9f020771";
ALTER TABLE lobbies DROP CONSTRAINT IF EXISTS club_id;
ALTER TABLE lobbies DROP COLUMN IF EXISTS club_id;
DROP TABLE IF EXISTS clubs;
