name: Run Migrations

on:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
      - name: Run Migrations
        run: |
          ./migrate -database "$DATABASE_URL" -path "migrations" -verbose up
        env:
          DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
